site_name: MeKoRP Docs
theme:
  name: 'material'
  language: de
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  favicon: assets/favicon.ico
  logo: assets/MeKo_Logo.png
  features:
    - content.action.view
    - content.action.edit
    - content.code.copy
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    # - navigation.footer
    # - navigation.path
    #- navigation.sections
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: custom
      accent: custom

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: custom
      accent: custom
markdown_extensions:
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
      linenums_style: table
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
repo_url: https://github.com/TobiasMeKo/test
repo_name: TobiasMeKo/wiki
edit_uri: edit/main/docs/
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - git-committers:
      repository: TobiasMeKo/test
      branch: main
  - search
extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
